# time
project_name: !!str "timelapse-january-2024-front"
interval: !!int 300
number_of_images: !!int -1

# image configuration
resolution: 
  width: !!int 2550
  height: !!int 1440
file_type: !!str "jpeg"

# where to save images
save_local: !!bool False
local_save_location: !!str ""

save_to_s3: !!bool True
s3_bucket_name: !!str "ginkgo-house-timelapse"
s3_path: !!str ""

# other
night_mode: !!bool False
exposure_time: !!int 10000000