# time
project_name: !!str "first-timelapse"
interval: !!int 20
number: !!int -1

# image configuration
resolution: 
  width: !!int 2550
  height: !!int 1440
file_type: !!str "jpeg"

# where to save images
local: !!bool True
local_save_location: !!str ""

save_to_s3: !!bool False
s3_bucket_name: !!str ""
s3_path: !!str ""

# other
night_mode: !!bool false
exposure_time: !!int 10000000